### ISSUE TITLE
implementing closeness 

### ISSUE THREAD

**Issue by ronaldFeri** [otherwise777/Temporal_Graph_library#2]
Hi, 
I want to implement closeness and but no luck yet. I was wondering if you could tell me how to implement it in Gelly(without Tink). I see your closeness version for Tink and got the general plan, but I don't know how to write compute method in runVertexCentricIteration model. Sorry for the irrelevant  question.

**Comment by otherwise777** [comment]
I see you've closed the ticket, please let me know if you still need help
